version: '2'

services:
  app:
    image: 10.10.0.1:5000/killerbot:master
    restart: always
    environment:
    - MYSQL_DATABASE=
    - MYSQL_USER=
    - MYSQL_PASSWORD=
    - DISCORD_KEY=
    networks:
      - backend
    depends_on:
      - db
  db:
    image: mariadb:latest
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_DATABASE=
    - MYSQL_USER=
    - MYSQL_PASSWORD=
    networks:
      - backend
    volumes:
    - "killerbot.database:/var/lib/mysql"
networks:
  backend:
